/**
 * Canonical Universe — Personal Finance Demo Data
 *
 * Single source of truth for all screen data.
 * B2C personal finance narrative for MIT Professional Education capstone.
 * Demo persona: Shinji Fujiwara — $180K total comp ($150K base + $30K RSUs), ~$94K net worth.
 */
import { DEMO_THREAD } from '@/lib/demo-thread'
import type {
  AccountEntity,
  CanonicalEvent,
  CanonicalUniverseV1,
  DashboardActivityEntity,
  DeliberationTrace,
  ExecuteActionEntity,
  GoalEntity,
  GovernAuditEntryEntity,
  GrowthSimulationPoint,
  ProtectThreatEntity,
  RecommendationDetail,
  RecommendationEntity,
  RecommendationListItem,
  ThreatFactor,
  ThreatTiming,
} from './types'
import type { ExecutionType } from './types'

const VERIFIED_DECISIONS = 59
const PENDING_REVIEW_DECISIONS = 6
const FLAGGED_DECISIONS = 2

// ─── Dashboard Activities ────────────────────────────────────────────────────

const DASHBOARD_ACTIVITIES: DashboardActivityEntity[] = [
  {
    id: 'ACT-001',
    kind: 'protect',
    label: 'Unusual login detected from Oslo, Norway at 3:42 AM',
    relativeTime: '5h ago',
  },
  {
    id: 'ACT-002',
    kind: 'protect',
    label: `Suspicious transaction: $${DEMO_THREAD.criticalAlert.amount} at ${DEMO_THREAD.criticalAlert.counterparty}`,
    relativeTime: '5h ago',
  },
  {
    id: 'ACT-003',
    kind: 'grow',
    label: 'High-yield savings transfer proposed — projected $269/yr advantage',
    relativeTime: '1h ago',
  },
  {
    id: 'ACT-004',
    kind: 'execute',
    label: 'Dividend reinvestment completed — $847.32 into VXUS',
    relativeTime: 'Yesterday',
  },
  {
    id: 'ACT-005',
    kind: 'govern',
    label: `Automated audit check passed (${DEMO_THREAD.complianceScore}/100)`,
    relativeTime: 'Yesterday',
  },
  {
    id: 'ACT-006',
    kind: 'system',
    label: 'Tax-loss harvesting deadline approaching — $399.60 potential savings',
    relativeTime: '2h ago',
  },
  {
    id: 'ACT-007',
    kind: 'protect',
    label: 'Unrecognized recurring charge detected — DIGISRV*PREMIUM $9.99/mo',
    relativeTime: '1d ago',
  },
  {
    id: 'ACT-008',
    kind: 'protect',
    label: 'Micro-transaction testing pattern flagged — 4 merchants, $4.36 total',
    relativeTime: '9d ago',
  },
  {
    id: 'ACT-009',
    kind: 'grow',
    label: '401(k) employer match gap detected — capturing $125/mo more saves $1,500/yr',
    relativeTime: '1d ago',
  },
]

// ─── Protect Evidence Data ──────────────────────────────────────────────────

const THREAT_TIMING: Record<string, ThreatTiming> = {
  'THR-001': { detected: '2026-03-10T03:42:00-07:00', updated: '2026-03-10T03:44:00-07:00', times: ['03:42', '03:43', '03:44', '03:45'] },
  'THR-002': { detected: '2026-03-10T03:47:00-07:00', updated: '2026-03-10T03:49:00-07:00', times: ['03:47', '03:48', '03:49', '03:50'] },
  'THR-003': { detected: '2026-01-15T09:00:00-08:00', updated: '2026-01-15T09:02:00-08:00', times: ['09:00', '09:01', '09:02', '09:03'] },
  'THR-004': { detected: '2026-02-15T10:00:00-08:00', updated: '2026-02-15T10:02:00-08:00', times: ['10:00', '10:01', '10:02', '10:03'] },
  'THR-005': { detected: '2026-03-08T14:15:00-07:00', updated: '2026-03-08T14:17:00-07:00', times: ['14:15', '14:16', '14:17', '14:18'] },
  'THR-006': { detected: '2026-03-09T08:30:00-07:00', updated: '2026-03-09T08:32:00-07:00', times: ['08:30', '08:31', '08:32', '08:33'] },
  'THR-007': { detected: '2026-02-28T10:00:00-08:00', updated: '2026-02-28T10:02:00-08:00', times: ['10:00', '10:01', '10:02', '10:03'] },
  'THR-008': { detected: '2026-03-05T09:15:00-07:00', updated: '2026-03-05T09:17:00-07:00', times: ['09:15', '09:16', '09:17', '09:18'] },
  'THR-009': { detected: '2026-03-01T15:42:00-07:00', updated: '2026-03-01T15:44:00-07:00', times: ['15:42', '15:43', '15:44', '15:45'] },
  'THR-010': { detected: '2026-02-20T11:00:00-08:00', updated: '2026-02-20T11:02:00-08:00', times: ['11:00', '11:01', '11:02', '11:03'] },
}
const DEFAULT_THREAT_TIMING: ThreatTiming = { detected: '2026-03-10T09:00:00-07:00', updated: '2026-03-10T09:02:00-07:00', times: ['09:00', '09:01', '09:02', '09:03'] }

const THREAT_FACTORS: Record<string, ThreatFactor[]> = {
  /* ── THR-001: Unusual Login from Oslo, Norway ── */
  'THR-001': [
    { id: 'e1', title: 'Geographic Anomaly', weight: 0.95, heroCue: 'First login from Norway — 5,200 miles from home', details: 'Login originated from Oslo, Norway — 5,200 miles from your San Francisco home. No prior logins from this region in your 3-year account history. Geographic deviation of this magnitude triggers high-confidence anomaly detection.', model: 'GeoNet-Sequence v2.0' },
    { id: 'e2', title: 'Device Fingerprint Mismatch', weight: 0.88, heroCue: 'Windows 11 + Chrome — user\'s known devices are MacOS + iPhone', details: 'Login device identified as Windows 11 with Chrome 122. Your known device profile consists of MacOS (MacBook Pro) and iOS (iPhone 15 Pro). This device has never been associated with your account.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e3', title: 'Time Pattern', weight: 0.82, heroCue: '3:42 AM PST — only 0.8% of user activity at this hour', details: 'Login occurred at 3:42 AM PST. Your 3-year activity history shows only 0.8% of logins between midnight and 6 AM. Off-hours access from a foreign IP is a high-risk indicator.', model: 'LSTM-TemporalSeq v2.0' },
    { id: 'e4', title: 'VPN Exit Node', weight: 0.75, heroCue: 'Connection through known VPN provider exit node', details: 'The originating IP (194.19.235.xxx) is registered to a known commercial VPN provider exit node in Oslo. VPN-based access from unrecognized locations is associated with credential-stuffing attacks.', model: 'GNN-Velocity v1.5' },
    { id: 'e5', title: 'Known Attack Pattern', weight: 0.85, heroCue: 'Matches 2,341 confirmed credential-stuffing cases', details: 'Login feature vector (foreign IP + unknown device + off-hours + VPN exit node) matches 2,341 confirmed credential-stuffing cases across the platform. Similarity score: 0.91.', model: 'GBM-FraudDetection v3.0' },
    { id: 'm1', title: 'Account Standing', weight: 0.60, details: 'Your Chase checking account has been active for 3+ years with no prior security incidents. Strong account health score: 0.94. Long-standing accounts with clean history have lower baseline fraud rates.', model: 'AE-AccountHealth v2.0', mitigating: true },
    { id: 'm2', title: 'No Transaction Attempt', weight: 0.55, details: 'The session was limited to login only — no funds transfer, bill pay, or account modification was attempted. Login-only events without subsequent financial actions have a 35% lower confirmed-fraud rate.', model: 'BayesNet-ActionSequence v1.8', mitigating: true },
  ],
  /* ── THR-002: Suspicious Transaction — Oslo Electronics $234.50 ── */
  'THR-002': [
    { id: 'e1', title: 'Merchant History', weight: 0.92, heroCue: 'First-ever transaction with this merchant', details: '$234.50 charge from OSLO ELECTRONICS — this merchant has never appeared in your transaction history. First-time merchant purchases from foreign locations trigger enhanced monitoring.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e2', title: 'Geographic Pattern', weight: 0.88, heroCue: 'Transaction in Oslo correlates with suspicious login 5 minutes prior', details: 'This transaction occurred in Oslo, Norway — the same location as the suspicious login detected 5 minutes earlier (THR-001). Geographic correlation between a flagged login and subsequent purchase is a strong fraud indicator.', model: 'GeoNet-Sequence v2.0' },
    { id: 'e3', title: 'Transaction Type', weight: 0.78, heroCue: 'Card-not-present purchase', details: 'This was a card-not-present (CNP) transaction — the physical card was not used. CNP transactions have 2.5× higher fraud rates than card-present transactions with chip verification.', model: 'GNN-Velocity v1.5' },
    { id: 'e4', title: 'Timing Correlation', weight: 0.85, heroCue: '5 minutes after suspicious login from same region', details: 'Transaction posted at 3:47 AM PST — exactly 5 minutes after the suspicious Oslo login. This rapid login-to-purchase sequence matches confirmed account takeover patterns.', model: 'LSTM-TemporalSeq v2.0' },
    { id: 'e5', title: 'Amount Pattern', weight: 0.72, heroCue: 'Similar to typical credential-stuffing test amounts', details: '$234.50 falls within the $100-$500 range commonly used in credential-stuffing test purchases. Attackers typically test with mid-range amounts to avoid immediate detection while confirming card validity.', model: 'GBM-FraudDetection v3.0' },
    { id: 'm1', title: 'Card Active', weight: 0.55, details: 'Your Amex Gold ending 4821 is actively used and in good standing. Active cards with consistent payment history have lower baseline fraud rates.', model: 'AE-AccountHealth v2.0', mitigating: true },
    { id: 'm2', title: 'Merchant Category', weight: 0.45, details: 'Electronics is a legitimate retail category. While the specific merchant is unknown, the category itself is not inherently suspicious.', model: 'BayesNet-MerchantFamiliar v1.8', mitigating: true },
  ],
  /* ── THR-003: NYTimes Subscription Price Increase ── */
  'THR-003': [
    { id: 'e1', title: 'Price Change Detected', weight: 0.82, heroCue: 'Monthly charge increased from $12.00 to $17.00 (+41.7%)', details: 'NYTimes subscription charge changed from $12.00/mo to $17.00/mo starting January 2026 billing cycle. A $5.00/month increase (41.7%) detected by comparing consecutive billing amounts.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e2', title: 'No Notification Detected', weight: 0.70, heroCue: 'No email or in-app notification detected for this price change', details: 'No corresponding price-change notification email, in-app alert, or proration charge was detected in the 30 days preceding this increase. Subscribers should be notified of rate changes before they take effect.', model: 'LSTM-TemporalSeq v2.0' },
    { id: 'e3', title: 'Above Average Increase', weight: 0.68, heroCue: '41.7% increase exceeds typical 5-10% annual adjustments', details: 'The 41.7% increase significantly exceeds the typical 5-10% annual subscription price adjustment. This magnitude of increase without prior notification warrants review.', model: 'XGB-MarketComparison v2.3' },
    { id: 'e4', title: 'Cohort Impact', weight: 0.65, heroCue: '8,400 users affected by this rate change', details: 'Across Poseidon users, 8,400 NYTimes subscribers experienced this same rate increase in January 2026. 22% chose to downgrade to a lower tier within 30 days of detection.', model: 'GBM-CohortImpact v3.0' },
    { id: 'e5', title: 'Duration Impact', weight: 0.60, heroCue: '$60/year cumulative impact', details: 'The $5.00/month increase results in $60/year additional cost. Over a typical 3-year subscription horizon, this represents $180 in cumulative additional spending.', model: 'GNN-SubscriptionTracker v1.5' },
    { id: 'm1', title: 'Service Continuity', weight: 0.55, details: 'You have maintained this NYTimes subscription for 18 consecutive months. Active subscriber with consistent engagement. Cancellation would lose digital archive access and saved articles.', model: 'AE-ServiceValue v2.0', mitigating: true },
    { id: 'm2', title: 'Budget Impact', weight: 0.40, details: 'The $5.00/month increase represents 0.077% of your monthly expenses ($6,500). Low absolute impact on overall budget.', model: 'BayesNet-BudgetImpact v1.8', mitigating: true },
  ],
  /* ── THR-004: Duplicate Charge — Adobe Creative Cloud $119.98 ── */
  'THR-004': [
    { id: 'e1', title: 'Duplicate Amount Match', weight: 0.92, heroCue: 'Two identical $59.99 charges on same day', details: 'Two charges of exactly $59.99 from Adobe Creative Cloud posted on February 15, 2026. Identical amount + same merchant + same day is a strong duplicate indicator.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e2', title: 'Same Day Billing', weight: 0.85, heroCue: 'Both charges on February 15, 2026', details: 'Both $59.99 charges appeared on the same billing date (February 15, 2026). Your Adobe CC subscription normally processes as a single monthly charge.', model: 'LSTM-TemporalSeq v2.0' },
    { id: 'e3', title: 'Single Subscription Pattern', weight: 0.78, heroCue: 'Only one Adobe CC subscription on file', details: 'Your account history shows a single Adobe Creative Cloud subscription with consistent $59.99 monthly billing. No plan upgrade, add-on, or second subscription was detected to explain the duplicate charge.', model: 'GNN-DuplicateDetector v1.5' },
    { id: 'e4', title: 'Known Issue Pattern', weight: 0.72, heroCue: 'Adobe has 1.8% duplicate charge rate across platform', details: 'Across Poseidon users, Adobe Creative Cloud has a 1.8% duplicate billing rate — 1.4× the platform average for SaaS subscriptions. Most duplicates are resolved within 5-7 business days when disputed.', model: 'XGB-MerchantReliability v2.3' },
    { id: 'e5', title: 'Amount Significance', weight: 0.68, heroCue: '$59.99 overcharge represents significant billing error', details: 'The $59.99 duplicate charge represents the full monthly subscription cost. This is not a partial or prorated charge, strongly suggesting a processing error rather than a legitimate secondary billing event.', model: 'GBM-FraudDetection v3.0' },
    { id: 'm1', title: 'Regular Merchant', weight: 0.60, details: 'Adobe Creative Cloud is a familiar merchant with 24+ months of consistent billing. Strong familiarity score: 0.93. Duplicates from established subscriptions are more likely processing errors than fraud.', model: 'AE-MerchantFamiliarity v2.0', mitigating: true },
    { id: 'm2', title: 'Billing Consistency', weight: 0.50, details: 'Prior months had single correct $59.99 charges. The duplicate is an anomaly against an otherwise consistent billing pattern — supporting the processing error hypothesis.', model: 'BayesNet-BillingPattern v1.8', mitigating: true },
  ],
  /* ── THR-005: Password Changed — Fidelity ── */
  'THR-005': [
    { id: 'e1', title: 'Account Change Event', weight: 0.65, heroCue: 'Password changed on investment account', details: 'Password was changed on your Fidelity investment account (401(k) + Roth IRA + Brokerage). Account credential changes on high-value investment accounts trigger standard security monitoring.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e2', title: 'Security Alert Triggered', weight: 0.55, heroCue: 'Standard monitoring notification', details: 'Fidelity password change triggered a standard security monitoring alert. All credential changes on accounts with balances exceeding $50,000 are flagged for verification.', model: 'GNN-Velocity v1.5' },
    { id: 'm1', title: 'Home IP Match', weight: 0.85, details: 'Password change originated from your San Francisco home IP address (Comcast residential). This IP has been associated with 98% of your Fidelity logins over the past 12 months.', model: 'GeoNet-Sequence v2.0', mitigating: true },
    { id: 'm2', title: 'User Confirmed', weight: 0.95, details: 'You dismissed this alert as intentional on March 8, 2026 at 2:15 PM. User confirmation resolves the security concern — no further action required.', model: 'AE-UserResponse v2.0', mitigating: true },
  ],
  /* ── THR-006: Unrecognized Recurring Charge — DIGISRV*PREMIUM ── */
  'THR-006': [
    { id: 'e1', title: 'Unknown Merchant', weight: 0.82, heroCue: 'DIGISRV*PREMIUM never appeared before December 2025', details: 'Recurring $9.99 charge from DIGISRV*PREMIUM has appeared on your Chase Sapphire Reserve for 3 consecutive months (Dec, Jan, Feb). This merchant has no prior history in your transaction records.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e2', title: 'Recurring Pattern', weight: 0.75, heroCue: '3 identical charges — $9.99 on the 5th of each month', details: 'The charge posts on the 5th of each month for exactly $9.99. Consistent recurring billing from an unrecognized source may indicate an unwanted subscription or trial conversion.', model: 'LSTM-TemporalSeq v2.0' },
    { id: 'e3', title: 'No Matching Service', weight: 0.70, heroCue: 'No email receipt or account found matching DIGISRV', details: 'No email confirmations, welcome messages, or account credentials were found in your connected email matching "DIGISRV" or "Digital Services Premium". This suggests a trial-to-paid conversion you may not have noticed.', model: 'GNN-SubscriptionTracker v1.5' },
    { id: 'e4', title: 'Cohort Pattern', weight: 0.65, heroCue: '1,200 users flagged same merchant — 78% confirmed unwanted', details: 'Across Poseidon users, 1,200 accounts show DIGISRV*PREMIUM charges. Of those who investigated, 78% confirmed the charge was unwanted (trial conversion). 94% received full refunds upon dispute.', model: 'GBM-CohortImpact v3.0' },
    { id: 'm1', title: 'Low Amount', weight: 0.50, details: '$9.99/month is below typical fraud thresholds. Small recurring charges are sometimes legitimate services the user forgot about.', model: 'AE-AmountAnalysis v2.0', mitigating: true },
    { id: 'm2', title: 'Consistent Billing', weight: 0.45, details: 'The charge amount and timing are perfectly consistent — typical of legitimate subscription billing rather than fraudulent activity.', model: 'BayesNet-BillingPattern v1.8', mitigating: true },
  ],
  /* ── THR-007: Utility Bill Spike — PG&E ── */
  'THR-007': [
    { id: 'e1', title: 'Bill Spike Detected', weight: 0.78, heroCue: '$387.42 — 109% above your 12-month average of $185', details: 'Your February PG&E bill of $387.42 is 109% above your 12-month rolling average of $185.21. This is the largest single-month deviation in your utility billing history.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e2', title: 'Seasonal Adjustment', weight: 0.68, heroCue: 'February bills typically 20-30% above average, not 109%', details: 'Winter months in San Francisco typically show 20-30% above-average utility bills. Your 109% spike significantly exceeds seasonal norms, suggesting a rate change, meter issue, or unusual consumption.', model: 'LSTM-TemporalSeq v2.0' },
    { id: 'e3', title: 'Rate Change Correlation', weight: 0.62, heroCue: 'PG&E implemented 12.8% rate increase in January 2026', details: 'PG&E implemented a 12.8% residential rate increase effective January 1, 2026. However, this rate change alone explains only $24 of the $202 increase — the remainder may indicate consumption change or billing error.', model: 'XGB-MarketComparison v2.3' },
    { id: 'e4', title: 'Cohort Comparison', weight: 0.58, heroCue: 'Your bill is in top 5% of SF residential customers', details: '$387.42 places you in the top 5% of San Francisco residential utility bills for February 2026. Median bill for similar-sized households: $225.', model: 'GBM-CohortImpact v3.0' },
    { id: 'm1', title: 'Known Provider', weight: 0.60, details: 'PG&E is your established utility provider with 3+ years of billing history. Spikes from known providers are more likely billing anomalies than fraud.', model: 'AE-MerchantFamiliarity v2.0', mitigating: true },
    { id: 'm2', title: 'Winter Season', weight: 0.50, details: 'February is historically your highest utility month. Some increase is expected due to heating demands, though the magnitude warrants review.', model: 'BayesNet-SeasonalPattern v1.8', mitigating: true },
  ],
  /* ── THR-008: Credit Card APR Increase — Chase Sapphire Reserve ── */
  'THR-008': [
    { id: 'e1', title: 'APR Increase Detected', weight: 0.80, heroCue: 'Variable APR increased from 22.49% to 24.99% (+2.5%)', details: 'Your Chase Sapphire Reserve variable APR increased from 22.49% to 24.99%, effective March 1, 2026. This 2.5 percentage point increase follows the Federal Reserve rate adjustment.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e2', title: 'Balance Impact', weight: 0.72, heroCue: '$890.45 current balance — $22/yr additional interest if carried', details: 'With your current balance of $890.45, the APR increase adds approximately $22/year in interest charges if the balance is carried. Impact scales with balance — at the $5,000 level, the cost would be $125/year.', model: 'GNN-FinancialImpact v1.5' },
    { id: 'e3', title: 'Fed Rate Correlation', weight: 0.68, heroCue: 'Follows 25bp Federal Reserve rate hike on Feb 12, 2026', details: 'The APR increase directly correlates with the Federal Reserve\'s 25 basis point rate increase on February 12, 2026. Variable APR cards typically adjust within 1-2 billing cycles.', model: 'XGB-MarketComparison v2.3' },
    { id: 'e4', title: 'Competitive Positioning', weight: 0.60, heroCue: '24.99% is above median premium card APR of 23.5%', details: 'Your new 24.99% APR is above the current median premium card APR of 23.5%. Balance transfer offers at 0% intro APR (12-15 months) are available from competitors.', model: 'GBM-CohortImpact v3.0' },
    { id: 'm1', title: 'Pay-in-Full History', weight: 0.70, details: 'You pay your Chase Sapphire balance in full 10 of 12 months. APR changes have minimal impact on users who rarely carry balances.', model: 'AE-PaymentBehavior v2.0', mitigating: true },
    { id: 'm2', title: 'Market-Wide Adjustment', weight: 0.55, details: 'This is a market-wide adjustment affecting all variable-rate cards, not a credit-risk-based increase specific to your account.', model: 'BayesNet-MarketContext v1.8', mitigating: true },
  ],
  /* ── THR-009: Micro-Transaction Testing Pattern ── */
  'THR-009': [
    { id: 'e1', title: 'Testing Pattern Detected', weight: 0.88, heroCue: '4 small charges ($0.50-$1.50) across different merchants in 12 minutes', details: 'Four small charges totaling $4.36 appeared on your Amex Gold in rapid succession: $0.50 (gas station), $1.00 (online retailer), $1.36 (convenience store), $1.50 (streaming service). This pattern matches card-testing behavior where stolen card numbers are validated with micro-charges.', model: 'GBM-FraudDetection v3.0' },
    { id: 'e2', title: 'Velocity Anomaly', weight: 0.85, heroCue: '4 transactions in 12 minutes — your average is 2.1/day', details: 'Your typical transaction frequency is 2.1 per day. Four transactions within a 12-minute window at 3:42 PM represents a 28× velocity spike. This rapid-fire pattern is a strong indicator of automated card testing.', model: 'GNN-Velocity v1.5' },
    { id: 'e3', title: 'Merchant Diversity', weight: 0.78, heroCue: 'All 4 merchants are first-time — never in your history', details: 'None of the four merchants have appeared in your transaction history. First-time merchant purchases across multiple categories in rapid succession is characteristic of card-testing fraud.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e4', title: 'Known Attack Vector', weight: 0.82, heroCue: 'Matches BIN attack pattern affecting Amex cards this quarter', details: 'This pattern matches a known BIN (Bank Identification Number) attack targeting Amex cards in Q1 2026. Attackers generate card numbers and test them with micro-charges before attempting larger purchases.', model: 'LSTM-TemporalSeq v2.0' },
    { id: 'm1', title: 'Small Total', weight: 0.40, details: 'Total exposure is only $4.36. If this is fraud, the damage is minimal. However, successful micro-tests typically precede larger fraudulent charges within 24-48 hours.', model: 'AE-AmountAnalysis v2.0', mitigating: true },
  ],
  /* ── THR-010: Data Breach — LinkedIn Email Exposure ── */
  'THR-010': [
    { id: 'e1', title: 'Breach Detection', weight: 0.72, heroCue: 'Your email found in LinkedIn data breach (Feb 2026)', details: 'Your email address (shinji@mit.com) was identified in a LinkedIn data breach disclosed on February 18, 2026. The breach exposed email addresses, hashed passwords, and professional profile data for approximately 12 million accounts.', model: 'GBM-BreachMonitor v3.0' },
    { id: 'e2', title: 'Credential Risk', weight: 0.65, heroCue: 'Hashed password included — credential stuffing risk elevated', details: 'The breach included bcrypt-hashed passwords. While bcrypt is resistant to brute-force attacks, sophisticated attackers may attempt credential stuffing using the email/password combination across other services.', model: 'IsoForest-Anomaly v4.1' },
    { id: 'e3', title: 'Cross-Service Risk', weight: 0.58, heroCue: 'Email matches 3 connected financial accounts', details: 'The exposed email address is associated with 3 of your connected financial accounts (Chase, Fidelity, Amex). If the LinkedIn password was reused, these accounts may be at elevated risk.', model: 'GNN-Velocity v1.5' },
    { id: 'm1', title: 'Password Unique', weight: 0.80, details: 'Based on your recent Fidelity password change and Chase 2FA enrollment, you appear to maintain unique passwords across financial accounts. This significantly reduces credential-stuffing risk.', model: 'AE-SecurityPosture v2.0', mitigating: true },
    { id: 'm2', title: '2FA Enabled', weight: 0.75, details: 'Two-factor authentication is enabled on all 3 connected financial accounts. Even if credentials were compromised, 2FA provides a strong secondary defense layer.', model: 'BayesNet-SecurityLayers v1.8', mitigating: true },
  ],
}

// ─── Protect Threats ────────────────────────────────────────────────────────

const PROTECT_THREATS: ProtectThreatEntity[] = [
  {
    id: 'THR-001',
    counterparty: 'Oslo, Norway — New Device',
    amountUsd: 0,
    confidence: 0.94,
    severity: 'High',
    status: 'pending',
    description: 'Login detected from Oslo, Norway using Chrome on Windows at 3:42 AM PST',
    relativeTime: '5h ago',
    sortOrder: 8,
    compositePriority: 95,
    timing: THREAT_TIMING['THR-001'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-001'],
    account: 'Chase Total Checking ••••3847',
    location: 'Oslo, Norway',
    flaggedIp: '194.19.235.xxx',
  },
  {
    id: 'THR-002',
    counterparty: 'OSLO ELECTRONICS',
    amountUsd: 234.50,
    confidence: 0.91,
    severity: 'High',
    status: 'pending',
    description: 'Card-not-present transaction at unknown merchant in Oslo, Norway',
    relativeTime: '5h ago',
    sortOrder: 7,
    compositePriority: 88,
    timing: THREAT_TIMING['THR-002'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-002'],
    account: 'Amex Gold ••••4821',
    location: 'Oslo, Norway',
  },
  {
    id: 'THR-003',
    counterparty: 'NYTimes',
    amountUsd: 17.00,
    confidence: 0.78,
    severity: 'Medium',
    status: 'pending',
    description: 'Monthly subscription increased from $12.00 to $17.00 (+41.7%) without notification',
    relativeTime: '2mo ago',
    sortOrder: 5,
    compositePriority: 55,
    timing: THREAT_TIMING['THR-003'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-003'],
  },
  {
    id: 'THR-004',
    counterparty: 'Adobe Creative Cloud',
    amountUsd: 119.98,
    confidence: 0.85,
    severity: 'Medium',
    status: 'pending',
    description: 'Duplicate charge — $59.99 charged twice on February 15, 2026',
    relativeTime: '23d ago',
    sortOrder: 4,
    compositePriority: 52,
    timing: THREAT_TIMING['THR-004'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-004'],
  },
  {
    id: 'THR-005',
    counterparty: 'Fidelity Investments',
    amountUsd: 0,
    confidence: 0.40,
    severity: 'Low',
    status: 'resolved',
    description: 'Password was changed from San Francisco IP — user confirmed as intentional',
    relativeTime: '2d ago',
    sortOrder: 1,
    compositePriority: 15,
    timing: THREAT_TIMING['THR-005'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-005'],
    resolvedAt: 'March 8, 2026 at 2:15 PM',
  },
  {
    id: 'THR-006',
    counterparty: 'DIGISRV*PREMIUM',
    amountUsd: 9.99,
    confidence: 0.72,
    severity: 'Medium',
    status: 'pending',
    description: 'Unrecognized recurring charge — $9.99/mo for 3 consecutive months with no matching service',
    relativeTime: '1d ago',
    sortOrder: 3,
    compositePriority: 48,
    timing: THREAT_TIMING['THR-006'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-006'],
    account: 'Chase Sapphire Reserve ••••9156',
  },
  {
    id: 'THR-007',
    counterparty: 'PG&E',
    amountUsd: 387.42,
    confidence: 0.65,
    severity: 'Low',
    status: 'pending',
    description: 'Utility bill spike — $387.42 is 109% above your 12-month average of $185',
    relativeTime: '10d ago',
    sortOrder: 2,
    compositePriority: 35,
    timing: THREAT_TIMING['THR-007'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-007'],
    account: 'Chase Total Checking ••••3847',
  },
  {
    id: 'THR-008',
    counterparty: 'Chase Sapphire Reserve',
    amountUsd: 0,
    confidence: 0.70,
    severity: 'Medium',
    status: 'pending',
    description: 'Credit card APR increased from 22.49% to 24.99% (+2.5%) following Fed rate hike',
    relativeTime: '5d ago',
    sortOrder: 3,
    compositePriority: 42,
    timing: THREAT_TIMING['THR-008'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-008'],
    account: 'Chase Sapphire Reserve ••••9156',
  },
  {
    id: 'THR-009',
    counterparty: 'Various (4 merchants)',
    amountUsd: 4.36,
    confidence: 0.82,
    severity: 'High',
    status: 'pending',
    description: 'Micro-transaction testing pattern — 4 small charges ($0.50-$1.50) across unknown merchants in 12 minutes',
    relativeTime: '9d ago',
    sortOrder: 6,
    compositePriority: 78,
    timing: THREAT_TIMING['THR-009'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-009'],
    account: 'Amex Gold ••••4821',
  },
  {
    id: 'THR-010',
    counterparty: 'LinkedIn',
    amountUsd: 0,
    confidence: 0.58,
    severity: 'Medium',
    status: 'resolved',
    description: 'Email found in LinkedIn data breach (Feb 2026) — password change recommended across linked accounts',
    relativeTime: '18d ago',
    sortOrder: 2,
    compositePriority: 30,
    timing: THREAT_TIMING['THR-010'] ?? DEFAULT_THREAT_TIMING,
    factors: THREAT_FACTORS['THR-010'],
    resolvedAt: 'February 22, 2026 at 10:30 AM',
  },
]

// ─── Recommendations (Summary Entities) ─────────────────────────────────────

const RECOMMENDATIONS: RecommendationEntity[] = [
  {
    id: 'REC-001',
    title: 'Move Idle Cash to High-Yield Savings',
    projectedBenefitUsd: 22,
    annualBenefitUsd: 269.40,
    confidence: 0.92,
    alternativeType: 'savings',
    compositePriority: Math.round(269 * 0.92 / 10),  // 25
  },
  {
    id: 'REC-002',
    title: 'Portfolio Rebalancing Opportunity',
    projectedBenefitUsd: 0,
    annualBenefitUsd: 0,
    confidence: 0.85,
    alternativeType: 'rebalance',
    compositePriority: 45,
  },
  {
    id: 'REC-003',
    title: 'Consolidate Streaming Subscriptions',
    projectedBenefitUsd: 18,
    annualBenefitUsd: 216,
    confidence: 0.84,
    alternativeType: 'subscription',
    compositePriority: Math.round(216 * 0.84 / 10),  // 18
  },
  {
    id: 'REC-004',
    title: 'Optimize Credit Card Points Strategy',
    projectedBenefitUsd: 16,
    annualBenefitUsd: 192,
    confidence: 0.88,
    alternativeType: 'savings',
    compositePriority: Math.round(192 * 0.88 / 10),  // 17
  },
  {
    id: 'REC-005',
    title: 'Increase 401(k) to Capture Full Employer Match',
    projectedBenefitUsd: 125,
    annualBenefitUsd: 1500,
    confidence: 0.95,
    alternativeType: 'savings',
    compositePriority: Math.round(1500 * 0.95 / 10),  // 143
  },
  {
    id: 'REC-006',
    title: 'Open 529 Education Savings Plan',
    projectedBenefitUsd: 0,
    annualBenefitUsd: 0,
    confidence: 0.82,
    alternativeType: 'savings',
    compositePriority: 40,
  },
  {
    id: 'REC-007',
    title: 'Negotiate Internet Bill (Rate Increase Detected)',
    projectedBenefitUsd: 25,
    annualBenefitUsd: 300,
    confidence: 0.76,
    alternativeType: 'savings',
    compositePriority: Math.round(300 * 0.76 / 10),  // 23
  },
  {
    id: 'REC-008',
    title: 'Daily Cash Pooling via FedNow Sweep',
    projectedBenefitUsd: 35,
    annualBenefitUsd: 420,
    confidence: 0.88,
    alternativeType: 'savings',
    compositePriority: Math.round(420 * 0.88 / 10),  // 37
  },
]

// ─── Execute Actions ────────────────────────────────────────────────────────

const EXECUTE_ACTIONS: ExecuteActionEntity[] = [
  {
    id: 'EXE-001',
    title: 'Tax-loss harvesting opportunity',
    engine: 'Grow',
    amountLabel: '$1,200 loss',
    confidence: 0.87,
    timestampLabel: '09:15',
    description: 'Sell VTI position to harvest $1,200 tax loss, saving $399.60 in taxes ($288 federal at 24% + $111.60 CA state at 9.3%).',
    urgency: 'high',
    impact: {
      approved: 'Tax loss of $1,200 harvested. Savings: $288 federal (24%) + $111.60 state CA (9.3%) = $399.60.',
      deferred: 'Tax-loss opportunity expires. Potential $399.60 savings lost if market recovers.',
    },
    reversible: false,
    expiresIn: '21d',
    factors: [
      { label: 'Tax Bracket Optimization', value: 0.92 },
      { label: 'Market Timing', value: 0.84 },
      { label: 'Wash Sale Compliance', value: 0.88 },
    ],
    executionType: 'semi-auto',
    category: 'investment',
    sourceEngine: 'Grow',
    riskTier: 2,
    compositePriority: 85,
    steps: [
      { id: 'EXE-001-S1', label: 'Analyze VTI position', description: 'Poseidon identified $1,200 unrealized loss in your VTI holdings — eligible for tax-loss harvesting before March 31 deadline', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-001-S2', label: 'Prepare sell order', description: 'Generated sell order for VTI shares with $1,200 loss. Replacement with ITOT to maintain market exposure while avoiding wash sale.', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '3s' },
      { id: 'EXE-001-S3', label: 'Approve sale', description: 'You review the tax-loss harvesting plan and authorize the VTI sell order in your Fidelity brokerage', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~2 min' },
      { id: 'EXE-001-S4', label: 'Track wash sale window', description: 'Poseidon monitors the 30-day wash sale window to prevent repurchase of substantially identical securities', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '30 days' },
    ],
  },
  {
    id: 'EXE-002',
    title: 'Monthly savings transfer',
    engine: 'Grow',
    amountLabel: '$500',
    confidence: 0.93,
    timestampLabel: '09:30',
    description: 'Set up monthly $500 transfer from Chase Checking to Marcus HYSA at 4.50% APY.',
    urgency: 'medium',
    impact: {
      approved: 'Recurring transfer scheduled. Builds toward high-yield savings goal.',
      deferred: '$500 remains in checking at 0.01% instead of 4.50% APY.',
    },
    reversible: true,
    expiresIn: null,
    factors: [
      { label: 'APY Differential', value: 0.95 },
      { label: 'Cash Flow Stability', value: 0.91 },
      { label: 'Liquidity Safety', value: 0.88 },
    ],
    executionType: 'auto',
    category: 'savings',
    sourceEngine: 'Grow',
    sourceEntityId: 'REC-001',
    rollbackWindowHours: 48,
    riskTier: 1,
    compositePriority: 70,
    steps: [
      { id: 'EXE-002-S1', label: 'Verify cash flow', description: 'Confirmed your checking balance supports a $500/month transfer with adequate remaining buffer for bills and expenses', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '1s' },
      { id: 'EXE-002-S2', label: 'Select destination account', description: 'Compared 12 high-yield savings accounts — Marcus by Goldman Sachs at 4.50% APY is the best match', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-002-S3', label: 'Approve recurring transfer', description: 'You confirm the $500/month transfer from Chase Checking to Marcus HYSA', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~30s' },
      { id: 'EXE-002-S4', label: 'Activate and monitor', description: 'Recurring transfer activated on the 1st of each month. Poseidon monitors balance and adjusts if cash flow changes', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: 'ongoing' },
    ],
  },
  {
    id: 'EXE-003',
    title: 'Dividend reinvestment — Q4 payout',
    engine: 'Grow',
    amountLabel: '$847.32',
    confidence: 0.91,
    timestampLabel: '11:20',
    description: 'Reinvest Q4 dividends into VXUS — 14.2 shares at $59.67.',
    urgency: 'low',
    impact: {
      approved: 'Dividends reinvested, compound growth continues.',
      deferred: 'Cash sits idle in brokerage account.',
    },
    reversible: true,
    expiresIn: null,
    factors: [
      { label: 'Compound Growth', value: 0.93 },
      { label: 'Allocation Fit', value: 0.89 },
      { label: 'Market Timing', value: 0.82 },
    ],
    executionType: 'auto',
    category: 'investment',
    sourceEngine: 'Grow',
    riskTier: 1,
    compositePriority: 45,
    steps: [
      { id: 'EXE-003-S1', label: 'Identify dividend payout', description: 'Q4 2025 dividends of $847.32 received in Fidelity Individual Brokerage account', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '1s' },
      { id: 'EXE-003-S2', label: 'Select reinvestment target', description: 'VXUS selected to increase international equity exposure per portfolio rebalancing plan', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-003-S3', label: 'Execute purchase', description: 'Purchased 14.2 shares of VXUS at $59.67 per share in Fidelity brokerage', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '3s' },
      { id: 'EXE-003-S4', label: 'Confirm settlement', description: 'Trade settled and shares added to portfolio. Updated allocation tracked by Poseidon', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2 days' },
    ],
  },
  {
    id: 'EXE-004',
    title: 'Cancel duplicate Adobe charge',
    engine: 'Protect',
    amountLabel: '$59.99',
    confidence: 0.85,
    timestampLabel: '10:02',
    description: 'File dispute for duplicate Adobe Creative Cloud charge on Feb 15.',
    urgency: 'medium',
    impact: {
      approved: 'Dispute filed. Refund of $59.99 expected within 5-7 business days.',
      deferred: 'Duplicate charge remains on statement. 60-day dispute window active.',
    },
    reversible: true,
    expiresIn: null,
    factors: [
      { label: 'Duplicate Amount Match', value: 0.94 },
      { label: 'Single Subscription', value: 0.88 },
      { label: 'Known Issue Rate', value: 0.78 },
    ],
    executionType: 'semi-auto',
    category: 'protection',
    sourceEngine: 'Protect',
    sourceEntityId: 'THR-004',
    riskTier: 1,
    compositePriority: 60,
    steps: [
      { id: 'EXE-004-S1', label: 'Compile evidence', description: 'Poseidon gathered transaction timestamps, subscription records, and billing history showing only one Adobe CC subscription', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-004-S2', label: 'Draft dispute', description: 'Generated dispute letter citing duplicate billing — two identical $59.99 charges on February 15 with single subscription confirmation', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-004-S3', label: 'Approve submission', description: 'You review the evidence and authorize Poseidon to file the duplicate charge dispute with Amex', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~1 min' },
      { id: 'EXE-004-S4', label: 'Track refund', description: 'Poseidon monitors the dispute status. Based on similar cases, refund expected within 5-7 business days', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '5-7 days' },
    ],
  },
  {
    id: 'EXE-005',
    title: 'Increase 401(k) contribution to 8%',
    engine: 'Grow',
    amountLabel: '$125/mo',
    confidence: 0.95,
    timestampLabel: '09:00',
    description: 'Increase 401(k) contribution from 4% to 8% to capture full employer match — $1,500/yr in free money.',
    urgency: 'medium',
    impact: {
      approved: 'Full employer match captured. Additional $125/mo employer contribution + your $125/mo increase.',
      deferred: '$1,500/year in employer matching left on the table.',
    },
    reversible: true,
    expiresIn: null,
    factors: [
      { label: 'Employer Match Gap', value: 0.96 },
      { label: 'Cash Flow Capacity', value: 0.90 },
      { label: 'Tax Benefit', value: 0.88 },
    ],
    executionType: 'semi-auto',
    category: 'investment',
    sourceEngine: 'Grow',
    sourceEntityId: 'REC-005',
    riskTier: 1,
    compositePriority: 90,
    steps: [
      { id: 'EXE-005-S1', label: 'Analyze payroll capacity', description: 'Confirmed your monthly cash flow supports an additional $375/mo pre-tax 401(k) deduction (4% → 8% of $150K base)', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-005-S2', label: 'Verify employer match terms', description: 'Your employer matches 100% up to 4% + 50% of next 4%. Increasing to 8% captures the full match: $125/mo additional employer contribution', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '1s' },
      { id: 'EXE-005-S3', label: 'Submit contribution change', description: 'You authorize the 401(k) contribution increase from 4% to 8% through your Fidelity benefits portal', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~3 min' },
      { id: 'EXE-005-S4', label: 'Confirm next payroll deduction', description: 'Poseidon verifies the updated deduction appears on your next paycheck and tracks ongoing match deposits', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '2 weeks' },
    ],
  },
  {
    id: 'EXE-006',
    title: 'Dispute unrecognized DIGISRV charge',
    engine: 'Protect',
    amountLabel: '$29.97',
    confidence: 0.72,
    timestampLabel: '08:32',
    description: 'File dispute for 3 months of unrecognized DIGISRV*PREMIUM charges ($9.99 × 3 = $29.97).',
    urgency: 'medium',
    impact: {
      approved: 'Dispute filed for $29.97. Future charges from this merchant flagged for rejection. Refund expected within 10 business days.',
      deferred: 'Unrecognized charges continue at $9.99/month.',
    },
    reversible: true,
    expiresIn: null,
    factors: [
      { label: 'Unknown Merchant', value: 0.82 },
      { label: 'Cohort Confirmation', value: 0.78 },
      { label: 'No Service Match', value: 0.70 },
    ],
    executionType: 'semi-auto',
    category: 'protection',
    sourceEngine: 'Protect',
    sourceEntityId: 'THR-006',
    riskTier: 1,
    compositePriority: 55,
    steps: [
      { id: 'EXE-006-S1', label: 'Compile charge history', description: 'Poseidon identified 3 consecutive $9.99 charges from DIGISRV*PREMIUM (Dec 5, Jan 5, Feb 5) with no matching service', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-006-S2', label: 'Draft dispute letter', description: 'Generated dispute documentation citing unrecognized recurring charges with no corresponding service agreement or email confirmation', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-006-S3', label: 'Approve dispute submission', description: 'You review the evidence and authorize Poseidon to file the dispute with Chase and prevent future charges from this merchant', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~1 min' },
      { id: 'EXE-006-S4', label: 'Monitor refund status', description: 'Poseidon tracks the dispute resolution and confirms the merchant is removed from future billing', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '10 days' },
    ],
  },
  {
    id: 'EXE-007',
    title: 'Negotiate Comcast internet rate',
    engine: 'Grow',
    amountLabel: '$25/mo',
    confidence: 0.76,
    timestampLabel: '09:45',
    description: 'Your Comcast internet increased from $79.99 to $104.99 after promo expired. Negotiate back to promotional rate.',
    urgency: 'low',
    impact: {
      approved: 'Retention offer secured. Expected savings: $25/mo ($300/yr).',
      deferred: 'Continue paying $104.99/mo — $25 above promotional rate.',
    },
    reversible: true,
    expiresIn: null,
    factors: [
      { label: 'Rate Increase Detection', value: 0.88 },
      { label: 'Retention Offer Likelihood', value: 0.76 },
      { label: 'Competitor Availability', value: 0.72 },
    ],
    executionType: 'semi-auto',
    category: 'savings',
    sourceEngine: 'Grow',
    sourceEntityId: 'REC-007',
    riskTier: 1,
    compositePriority: 50,
    steps: [
      { id: 'EXE-007-S1', label: 'Detect rate change', description: 'Poseidon detected Comcast billing increased from $79.99 to $104.99 — promotional period ended after 12 months', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '1s' },
      { id: 'EXE-007-S2', label: 'Research competitor offers', description: 'Compiled competitive offers: AT&T Fiber $70/mo, Sonic $65/mo — leverage for negotiation', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '3s' },
      { id: 'EXE-007-S3', label: 'Call retention department', description: 'You call Comcast retention (1-800-934-6489) with the competitor pricing Poseidon compiled. Script provided.', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~15 min' },
      { id: 'EXE-007-S4', label: 'Verify new rate', description: 'Poseidon monitors your next Comcast bill to confirm the negotiated rate is applied', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '1 billing cycle' },
    ],
  },
  {
    id: 'EXE-008',
    title: 'Enable nightly FedNow cash sweep',
    engine: 'Grow',
    amountLabel: '$35/mo',
    confidence: 0.88,
    timestampLabel: '10:15',
    description: 'Sweep idle Chase checking balance overnight to high-yield account via FedNow instant transfer, earning ~$35/mo at 4.5% APY.',
    urgency: 'medium',
    impact: {
      approved: 'Nightly sweep activated. ~$9,000 average idle balance earns 4.5% APY overnight instead of 0.01%. Net ~$35/mo.',
      deferred: 'Idle checking balance continues earning 0.01% — losing ~$420/yr in potential interest.',
    },
    reversible: true,
    expiresIn: null,
    factors: [
      { label: 'Idle Balance Detection', value: 0.92 },
      { label: 'FedNow Availability', value: 0.88 },
      { label: 'Liquidity Safety', value: 0.85 },
    ],
    executionType: 'auto',
    category: 'savings',
    sourceEngine: 'Grow',
    sourceEntityId: 'REC-008',
    riskTier: 1,
    compositePriority: 65,
    steps: [
      { id: 'EXE-008-S1', label: 'Analyze idle balance pattern', description: 'Your Chase checking averages $9,000 idle overnight after all scheduled payments clear. FedNow enables instant sweep and return.', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-008-S2', label: 'Select sweep destination', description: 'Marcus HYSA at 4.50% APY selected — FedNow-enabled, FDIC insured, instant transfer capability', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '1s' },
      { id: 'EXE-008-S3', label: 'Authorize nightly sweep', description: 'You set up the automated nightly sweep: transfer idle balance at 11 PM, return before 6 AM via FedNow instant rails', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~5 min' },
      { id: 'EXE-008-S4', label: 'Monitor sweep performance', description: 'Poseidon tracks nightly sweep amounts, interest earned, and ensures checking balance is restored before morning transactions', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: 'ongoing' },
    ],
  },
  {
    id: 'EXE-009',
    title: 'File micro-transaction fraud report',
    engine: 'Protect',
    amountLabel: '$4.36',
    confidence: 0.82,
    timestampLabel: '15:44',
    description: 'Report suspected card-testing micro-transactions and request new card number from Amex.',
    urgency: 'high',
    impact: {
      approved: 'Card flagged for replacement. 4 micro-charges disputed. New card number issued within 2 business days.',
      deferred: 'Card remains potentially compromised. Larger fraudulent charges may follow within 24-48 hours.',
    },
    reversible: false,
    expiresIn: '48h',
    factors: [
      { label: 'Testing Pattern Match', value: 0.88 },
      { label: 'Velocity Anomaly', value: 0.85 },
      { label: 'BIN Attack Correlation', value: 0.82 },
    ],
    executionType: 'semi-auto',
    category: 'protection',
    sourceEngine: 'Protect',
    sourceEntityId: 'THR-009',
    riskTier: 2,
    compositePriority: 88,
    steps: [
      { id: 'EXE-009-S1', label: 'Compile evidence', description: 'Poseidon documented 4 micro-charges totaling $4.36 across unknown merchants in a 12-minute window — matches card-testing pattern', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-009-S2', label: 'Prepare fraud report', description: 'Generated fraud report with transaction timestamps, merchant details, and BIN attack correlation evidence', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-009-S3', label: 'Approve card replacement', description: 'You authorize Poseidon to file the fraud report with Amex and request a replacement card with a new number', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~2 min' },
      { id: 'EXE-009-S4', label: 'Track replacement and disputes', description: 'Poseidon monitors the card replacement delivery and ensures all 4 micro-charges are credited back', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '2-5 days' },
    ],
  },
]

// ─── Govern Audit Entries ───────────────────────────────────────────────────

function governPriority(status: 'Verified' | 'Pending review' | 'Flagged', confidence: number): number {
  const statusWeight = status === 'Pending review' ? 90 : status === 'Flagged' ? 80 : 40
  return Math.round(statusWeight + confidence * 10)
}

const GOVERN_AUDIT_ENTRIES: GovernAuditEntryEntity[] = [
  {
    id: 'GV-2026-0310-001',
    timestampIso: '2026-03-10T03:42:00-07:00',
    type: 'Protect',
    action: 'Unusual login flagged — Oslo, Norway',
    confidence: 0.94,
    evidence: 5,
    status: 'Pending review',
    compositePriority: governPriority('Pending review', 0.94),
  },
  {
    id: 'GV-2026-0310-002',
    timestampIso: '2026-03-10T03:47:00-07:00',
    type: 'Protect',
    action: 'Suspicious transaction flagged — Oslo Electronics $234.50',
    confidence: 0.91,
    evidence: 5,
    status: 'Pending review',
    compositePriority: governPriority('Pending review', 0.91),
  },
  {
    id: 'GV-2026-0310-003',
    timestampIso: '2026-03-10T09:15:00-07:00',
    type: 'Grow',
    action: 'High-yield savings opportunity — $269/yr',
    confidence: 0.92,
    evidence: 4,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.92),
  },
  {
    id: 'GV-2026-0309-004',
    timestampIso: '2026-03-09T16:30:00-07:00',
    type: 'Grow',
    action: 'Portfolio rebalancing recommendation generated',
    confidence: 0.85,
    evidence: 4,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.85),
  },
  {
    id: 'GV-2026-0308-005',
    timestampIso: '2026-03-08T09:00:00-07:00',
    type: 'Protect',
    action: 'Fidelity password change detected',
    confidence: 0.40,
    evidence: 3,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.40),
  },
  {
    id: 'GV-2026-0307-006',
    timestampIso: '2026-03-07T11:20:00-07:00',
    type: 'Execute',
    action: 'Dividend reinvestment auto-executed',
    confidence: 0.91,
    evidence: 4,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.91),
  },
  {
    id: 'GV-2026-0309-007',
    timestampIso: '2026-03-09T08:30:00-07:00',
    type: 'Protect',
    action: 'Unrecognized recurring charge flagged — DIGISRV*PREMIUM',
    confidence: 0.72,
    evidence: 4,
    status: 'Pending review',
    compositePriority: governPriority('Pending review', 0.72),
  },
  {
    id: 'GV-2026-0228-008',
    timestampIso: '2026-02-28T10:00:00-08:00',
    type: 'Protect',
    action: 'Utility bill spike detected — PG&E $387.42',
    confidence: 0.65,
    evidence: 4,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.65),
  },
  {
    id: 'GV-2026-0305-009',
    timestampIso: '2026-03-05T09:15:00-07:00',
    type: 'Protect',
    action: 'APR increase notification — Chase Sapphire Reserve +2.5%',
    confidence: 0.70,
    evidence: 4,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.70),
  },
  {
    id: 'GV-2026-0301-010',
    timestampIso: '2026-03-01T15:42:00-07:00',
    type: 'Protect',
    action: 'Micro-transaction testing pattern flagged — 4 merchants',
    confidence: 0.82,
    evidence: 4,
    status: 'Pending review',
    compositePriority: governPriority('Pending review', 0.82),
  },
  {
    id: 'GV-2026-0220-011',
    timestampIso: '2026-02-20T11:00:00-08:00',
    type: 'Protect',
    action: 'Data breach notification — LinkedIn email exposure',
    confidence: 0.58,
    evidence: 4,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.58),
  },
  {
    id: 'GV-2026-0309-012',
    timestampIso: '2026-03-09T09:00:00-07:00',
    type: 'Grow',
    action: '401(k) employer match optimization — $1,500/yr opportunity',
    confidence: 0.95,
    evidence: 3,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.95),
  },
  {
    id: 'GV-2026-0308-013',
    timestampIso: '2026-03-08T14:00:00-07:00',
    type: 'Grow',
    action: '529 education savings recommendation generated',
    confidence: 0.82,
    evidence: 3,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.82),
  },
  {
    id: 'GV-2026-0307-014',
    timestampIso: '2026-03-07T09:45:00-07:00',
    type: 'Grow',
    action: 'Internet bill negotiation opportunity — Comcast rate increase',
    confidence: 0.76,
    evidence: 3,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.76),
  },
  {
    id: 'GV-2026-0306-015',
    timestampIso: '2026-03-06T10:15:00-07:00',
    type: 'Grow',
    action: 'Daily cash pooling opportunity — FedNow sweep optimization',
    confidence: 0.88,
    evidence: 3,
    status: 'Verified',
    compositePriority: governPriority('Verified', 0.88),
  },
]

// ─── Deliberation Traces ────────────────────────────────────────────────────

const EVT_001_DELIBERATION: DeliberationTrace = {
  id: 'DT-001',
  eventId: 'EVT-001',
  rounds: [
    {
      roleId: 'fraud-detection',
      modelId: 'claude-sonnet-4-6',
      position: 'support',
      argument: 'Suspicious login from Oslo, Norway followed by a $234.50 card-not-present purchase 5 minutes later. Geographic anomaly (5,200 miles from home), unknown device (Windows/Chrome vs user\'s MacOS/iPhone), and off-hours timing (3:42 AM PST) all match credential-stuffing patterns. Pattern similarity to 2,341 confirmed cases is 0.91. Recommend immediate freeze and dispute preparation.',
      confidence: 0.94,
      factors: [
        { label: 'Geographic anomaly confidence', weight: 0.30 },
        { label: 'Login-to-purchase correlation', weight: 0.25 },
        { label: 'Device fingerprint mismatch', weight: 0.25 },
        { label: 'Timing pattern deviation', weight: 0.20 },
      ],
    },
    {
      roleId: 'behavioral-analytics',
      modelId: 'gpt-4o',
      position: 'modify',
      argument: 'While the Oslo login and purchase are correlated, the user could be traveling or using a VPN. However, no travel-related searches, flight bookings, or hotel charges were detected in the past 30 days. The VPN exit node is from a commercial provider frequently associated with credential leaks. Recommend flagging with user verification — do not auto-freeze without consent.',
      confidence: 0.82,
      factors: [
        { label: 'Travel pattern analysis', weight: 0.35 },
        { label: 'VPN provider risk score', weight: 0.30 },
        { label: 'User behavioral baseline', weight: 0.20 },
        { label: 'Account activity context', weight: 0.15 },
      ],
    },
    {
      roleId: 'financial-strategy',
      modelId: 'claude-opus-4-6',
      position: 'support',
      argument: 'The combined risk exposure is $234.50 (transaction) plus potential unauthorized access to checking account ($12,450 balance). Given the strength of correlated indicators (login + purchase in same foreign location within 5 minutes), the cost of a false negative far outweighs the inconvenience of a false positive. Recommend preparing dispute package and temporary card freeze pending user confirmation.',
      confidence: 0.91,
      factors: [
        { label: 'Total exposure assessment', weight: 0.35 },
        { label: 'Correlation strength', weight: 0.25 },
        { label: 'False negative cost analysis', weight: 0.25 },
        { label: 'User disruption minimization', weight: 0.15 },
      ],
    },
    {
      roleId: 'policy-engine',
      modelId: 'system-policy-engine',
      position: 'support',
      argument: 'Regulation E requires notification within 60 days of unauthorized electronic fund transfers. The suspicious login triggers immediate user notification. Card-not-present transaction dispute is eligible under zero-liability policy. Human authorization is required before filing dispute or freezing card. Proceed with flag, evidence compilation, and user notification.',
      confidence: 1.0,
      factors: [
        { label: 'Regulatory compliance window', weight: 0.40 },
        { label: 'Zero-liability policy eligibility', weight: 0.30 },
        { label: 'Human consent requirement', weight: 0.20 },
        { label: 'Evidence preservation duty', weight: 0.10 },
      ],
    },
  ],
  consensus: {
    score: 0.91,
    adoptedModelId: 'claude-opus-4-6',
    rationale: 'Council consensus: flag the suspicious login and correlated Oslo Electronics transaction, prepare a dispute package, and present evidence to the user for final decision. Fraud detection AI identified strong geographic and temporal correlation, behavioral analytics confirmed no travel indicators, financial strategy AI assessed the risk-reward favors proactive preparation, and the policy engine verified regulatory compliance and zero-liability eligibility. The user retains full authority to approve or dismiss.',
  },
}

// ─── Canonical Events ───────────────────────────────────────────────────────

const CANONICAL_EVENTS: CanonicalEvent[] = [
  {
    id: 'EVT-001',
    title: 'Suspicious login + transaction — Oslo, Norway',
    timestampIso: '2026-03-10T03:42:00-07:00',
    status: 'active',
    children: {
      threats: ['THR-001', 'THR-002'],
      alternatives: [],
      actions: ['EXE-004'],
      auditEntries: ['GV-2026-0310-001', 'GV-2026-0310-002'],
    },
    deliberationTraces: [EVT_001_DELIBERATION],
  },
  {
    id: 'EVT-002',
    title: 'Tax-loss harvesting opportunity — VTI position',
    timestampIso: '2026-03-10T09:15:00-07:00',
    status: 'active',
    children: {
      threats: [],
      alternatives: ['REC-001', 'REC-002'],
      actions: ['EXE-001'],
      auditEntries: ['GV-2026-0310-003', 'GV-2026-0309-004'],
    },
    deliberationTraces: [],
  },
  {
    id: 'EVT-003',
    title: 'Dividend reinvestment — Q4 payout',
    timestampIso: '2026-03-07T11:20:00-07:00',
    status: 'active',
    children: {
      threats: [],
      alternatives: [],
      actions: ['EXE-003'],
      auditEntries: ['GV-2026-0307-006'],
    },
    deliberationTraces: [],
  },
  {
    id: 'EVT-004',
    title: 'Unrecognized recurring charge — DIGISRV*PREMIUM',
    timestampIso: '2026-03-09T08:30:00-07:00',
    status: 'active',
    children: {
      threats: ['THR-006'],
      alternatives: [],
      actions: ['EXE-006'],
      auditEntries: ['GV-2026-0309-007'],
    },
    deliberationTraces: [],
  },
  {
    id: 'EVT-005',
    title: 'Micro-transaction card testing detected',
    timestampIso: '2026-03-01T15:42:00-07:00',
    status: 'active',
    children: {
      threats: ['THR-009'],
      alternatives: [],
      actions: ['EXE-009'],
      auditEntries: ['GV-2026-0301-010'],
    },
    deliberationTraces: [],
  },
  {
    id: 'EVT-006',
    title: 'Retirement & education savings optimization',
    timestampIso: '2026-03-09T09:00:00-07:00',
    status: 'active',
    children: {
      threats: [],
      alternatives: ['REC-005', 'REC-006'],
      actions: ['EXE-005'],
      auditEntries: ['GV-2026-0309-012', 'GV-2026-0308-013'],
    },
    deliberationTraces: [],
  },
  {
    id: 'EVT-007',
    title: 'Bill optimization & cash management',
    timestampIso: '2026-03-07T09:45:00-07:00',
    status: 'active',
    children: {
      threats: [],
      alternatives: ['REC-007', 'REC-008'],
      actions: ['EXE-007', 'EXE-008'],
      auditEntries: ['GV-2026-0307-014', 'GV-2026-0306-015'],
    },
    deliberationTraces: [],
  },
]

// ─── Growth Simulation Data ─────────────────────────────────────────────────

export const CANONICAL_GROWTH_SIMULATION_DATA: GrowthSimulationPoint[] = [
  { year: 'Now', baseline: 94041, aiOptimized: 94041, low: 94041, high: 94041 },
  { year: '3M',  baseline: 94276, aiOptimized: 96393, low: 96100, high: 96700 },
  { year: '6M',  baseline: 94512, aiOptimized: 98811, low: 98300, high: 99400 },
  { year: '9M',  baseline: 94748, aiOptimized: 101298, low: 100500, high: 102200 },
  { year: '1Y',  baseline: 94985, aiOptimized: 103855, low: 102800, high: 105000 },
  { year: '15M', baseline: 95223, aiOptimized: 106458, low: 105200, high: 107800 },
  { year: '18M', baseline: 95461, aiOptimized: 109128, low: 107600, high: 110750 },
  { year: '21M', baseline: 95699, aiOptimized: 111867, low: 110100, high: 113750 },
  { year: '2Y',  baseline: 95938, aiOptimized: 114675, low: 112700, high: 116800 },
  { year: '27M', baseline: 96178, aiOptimized: 117555, low: 115400, high: 119900 },
  { year: '30M', baseline: 96419, aiOptimized: 120509, low: 118200, high: 123050 },
  { year: '33M', baseline: 96660, aiOptimized: 123540, low: 121100, high: 126250 },
  { year: '3Y',  baseline: 96901, aiOptimized: 126650, low: 124000, high: 129500 },
]

const FINAL_SIM = CANONICAL_GROWTH_SIMULATION_DATA[CANONICAL_GROWTH_SIMULATION_DATA.length - 1]
export const CANONICAL_PROJECTED_3Y_ADVANTAGE = FINAL_SIM.aiOptimized - FINAL_SIM.baseline

// ─── Recommendation Detail Data ─────────────────────────────────────────────

const REC_TO_AUDIT_ID: Record<number, string> = {
  1: 'GV-2026-0310-003',
  2: 'GV-2026-0309-004',
  3: 'GV-2026-0309-004',
  4: 'GV-2026-0310-003',
  5: 'GV-2026-0309-012',
  6: 'GV-2026-0308-013',
  7: 'GV-2026-0307-014',
  8: 'GV-2026-0306-015',
}

const growModelInfo = (recNum: number) => ({
  name: 'GrowthOptimizer' as const,
  version: '3.2',
  accuracy: 0.912,
  auditId: REC_TO_AUDIT_ID[recNum] ?? `GV-2026-0310-R${String(recNum).padStart(2, '0')}`,
})

export const CANONICAL_RECOMMENDATION_DETAILS: RecommendationDetail[] = [
  {
    id: 1, title: 'Move Idle Cash to High-Yield Savings', category: 'Efficiency',
    monthlySavings: 22, annualSavings: 269, confidence: 0.92,
    dataBasis: 'Based on 14 months of checking and savings account data',
    situationLabel: 'Your Savings Account',
    currentItems: [
      { name: 'Chase Savings (current)', cost: 0, usage: 'low', note: '$8,200 balance · 0.01% APY · earning $0.82/year' },
    ],
    currentTotal: 0,
    comparison: { kind: 'yield', currentApy: 0.01, newApy: 4.50, annualGain: 269 },
    insights: [
      'Your $8,200 in Chase Savings earns just $0.82/year at 0.01% APY',
      'High-yield savings accounts currently offer 4.50% APY — 450× your current rate',
      'Transferring $6,000 to a HYSA would earn approximately $269/year more in interest',
    ],
    changes: [
      { action: 'switch', item: 'Move $6,000 to high-yield savings', from: '0.01% APY ($0.60/yr)', to: '4.50% APY ($270/yr)', savings: 22 },
    ],
    newTotal: 0,
    alternatives: [
      { name: 'Marcus by Goldman Sachs', detail: '4.50% APY', note: 'No minimum balance, FDIC insured, easy transfers to Chase', recommended: true },
      { name: 'Ally Bank Online Savings', detail: '4.35% APY', note: 'No minimum, buckets feature for goal tracking', recommended: false },
      { name: 'Wealthfront Cash Account', detail: '4.25% APY', note: 'Integrated with investment accounts', recommended: false },
    ],
    ratesAsOf: 'Mar 10, 2026',
    steps: [
      { step: 1, title: 'Open high-yield savings account', description: 'Poseidon pre-fills your application for Marcus by Goldman Sachs. Takes about 5 minutes online.', type: 'semi-auto', estimatedTime: '5 minutes' },
      { step: 2, title: 'Transfer $6,000', description: 'Initiate a transfer of $6,000 from your Chase Savings. Funds arrive in 1-2 business days.', type: 'semi-auto', estimatedTime: '1-2 days' },
      { step: 3, title: 'Set up direct deposit split', description: 'Optional: redirect a portion of your paycheck to the new account for ongoing savings growth.', type: 'manual', estimatedTime: '10 minutes' },
    ],
    executionType: 'semi-auto',
    factors: [
      'Your $8,200 earning 0.01% APY is the primary signal — you\'re losing $269/year in potential interest on the first $6,000',
      'High-yield savings rates are at historic highs — the rate differential is the widest in 15 years',
      'FDIC insurance covers up to $250,000, so your entire balance is protected regardless of where you bank',
    ],
    cohortProof: '2,180 Poseidon users with similar savings balances who switched to high-yield accounts earned an average of $269/year more in interest',
    modelInfo: growModelInfo(1),
    dataSources: ['Connected savings account balance (14 months)', 'High-yield savings rate comparison (18 providers)', 'FDIC insurance verification'],
  },
  {
    id: 2, title: 'Portfolio Rebalancing Opportunity', category: 'Risk Mitigation',
    monthlySavings: 0, annualSavings: 0, confidence: 0.85,
    dataBasis: 'Based on your connected 401(k), Roth IRA, and brokerage holdings',
    situationLabel: 'Your Portfolio Allocation',
    currentItems: [
      { name: 'US Equities (VTI)', cost: 0, usage: 'high', note: '65% of portfolio — target is 60%' },
      { name: 'International Equities (VXUS)', cost: 0, usage: 'low', note: '20% of portfolio — target is 25%' },
      { name: 'Bonds (BND)', cost: 0, usage: 'medium', note: '15% of portfolio — on target' },
    ],
    currentTotal: 0,
    comparison: { kind: 'allocation', currentMix: 'US 65% / Int\'l 20% / Bonds 15%', newMix: 'US 60% / Int\'l 25% / Bonds 15%' },
    insights: [
      'Your international equities allocation is 5% below target — reducing diversification benefits',
      'Rebalancing within your Roth IRA (tax-free) avoids capital gains consequences',
      'Selling $2,300 VTI and buying $2,300 VXUS in the Roth IRA achieves target allocation at zero tax cost',
    ],
    changes: [
      { action: 'reduce', item: 'Reduce US equities from 65% to 60%', from: 'US 65% ($49,904)', to: 'US 60% ($46,073)', savings: 0 },
      { action: 'increase', item: 'Increase Int\'l equities from 20% to 25%', from: 'Int\'l 20% ($15,324)', to: 'Int\'l 25% ($19,155)', savings: 0 },
    ],
    newTotal: 0,
    alternatives: [],
    ratesAsOf: 'Mar 10, 2026',
    steps: [
      { step: 1, title: 'Review rebalancing plan', description: 'Poseidon shows the proposed allocation changes: sell $2,300 VTI, buy $2,300 VXUS in your Roth IRA.', type: 'auto', estimatedTime: '2 minutes' },
      { step: 2, title: 'Execute trades in Roth IRA', description: 'Place the rebalancing trades within your Fidelity Roth IRA — tax-free transactions.', type: 'semi-auto', estimatedTime: '5 minutes' },
      { step: 3, title: 'Set quarterly rebalance reminder', description: 'Poseidon schedules quarterly portfolio drift checks to maintain your target allocation.', type: 'auto', estimatedTime: 'ongoing' },
    ],
    executionType: 'semi-auto',
    factors: [
      'International equities underweight by 5% reduces geographic diversification — increases correlation risk during US market downturns',
      'Executing the rebalance in your Roth IRA means zero tax impact — unlike taxable accounts, there are no capital gains consequences',
      'Quarterly rebalancing keeps drift within 2% of target — maintaining the intended risk profile over time',
    ],
    cohortProof: 'Poseidon users who rebalanced to increase international exposure in 2025 saw 8% lower drawdowns during the Q3 market correction compared to US-concentrated portfolios',
    modelInfo: growModelInfo(2),
    dataSources: ['Connected 401(k) holdings', 'Roth IRA holdings', 'Brokerage holdings', 'Target allocation model'],
  },
  {
    id: 3, title: 'Consolidate Streaming Subscriptions', category: 'Efficiency',
    monthlySavings: 18, annualSavings: 216, confidence: 0.84,
    dataBasis: 'Based on 12 months of recurring subscription billing data across your cards',
    situationLabel: 'Your Streaming Subscriptions',
    currentItems: [
      { name: 'Netflix Premium', cost: 22.99, usage: 'high', note: '$22.99/mo · 4K + 4 screens · billed to Chase Sapphire' },
      { name: 'Hulu (No Ads)', cost: 17.99, usage: 'medium', note: '$17.99/mo · billed to Amex Gold' },
      { name: 'Disney+', cost: 13.99, usage: 'low', note: '$13.99/mo · billed to Amex Gold · 2 streams in last 30 days' },
      { name: 'HBO Max', cost: 15.99, usage: 'medium', note: '$15.99/mo · billed to Chase Sapphire' },
    ],
    currentTotal: 70.96,
    comparison: { kind: 'yield', currentApy: 70.96, newApy: 52.97, annualGain: 216 },
    insights: [
      'You\'re paying $70.96/month across 4 streaming services — Disney+ and Hulu have significant content overlap and are owned by the same parent company',
      'The Disney Bundle ($19.99/mo) replaces both Hulu and Disney+ individually ($31.98/mo), saving $11.99/month',
      'Downgrading Netflix from Premium ($22.99) to Standard ($15.49) saves $7.50/mo — you rarely use 4 simultaneous streams',
    ],
    changes: [
      { action: 'switch', item: 'Replace Hulu + Disney+ with Disney Bundle', from: 'Hulu $17.99 + Disney+ $13.99 = $31.98/mo', to: 'Disney Bundle $19.99/mo', savings: 12 },
      { action: 'reduce', item: 'Downgrade Netflix Premium to Standard', from: 'Netflix Premium $22.99/mo', to: 'Netflix Standard $15.49/mo', savings: 6 },
    ],
    newTotal: 52.97,
    alternatives: [
      { name: 'Disney Bundle (Duo)', detail: '$19.99/mo', note: 'Hulu (No Ads) + Disney+ — same content, one bill, $12/mo savings', recommended: true },
      { name: 'Netflix Standard', detail: '$15.49/mo', note: '1080p, 2 screens — sufficient for a household of 4', recommended: true },
      { name: 'Keep all 4 services', detail: '$70.96/mo', note: 'Maximum content library — no changes needed if budget allows', recommended: false },
    ],
    ratesAsOf: 'Mar 10, 2026',
    steps: [
      { step: 1, title: 'Subscribe to Disney Bundle', description: 'Sign up for the Disney Bundle Duo at $19.99/mo. Your existing Hulu and Disney+ watch history transfers automatically.', type: 'semi-auto', estimatedTime: '5 minutes' },
      { step: 2, title: 'Cancel individual Hulu and Disney+', description: 'Cancel the standalone Hulu ($17.99) and Disney+ ($13.99) subscriptions after confirming Disney Bundle is active.', type: 'semi-auto', estimatedTime: '5 minutes' },
      { step: 3, title: 'Downgrade Netflix to Standard', description: 'Change your Netflix plan from Premium ($22.99) to Standard ($15.49) in account settings.', type: 'semi-auto', estimatedTime: '2 minutes' },
    ],
    executionType: 'semi-auto',
    factors: [
      'Hulu and Disney+ are both owned by Disney — the Disney Bundle provides both services at a 37% discount vs. individual subscriptions',
      'Your Netflix usage data shows a maximum of 2 simultaneous streams in the past 90 days — Premium\'s 4-stream benefit is unused',
      'Total savings of $18/month ($216/year) with no content loss — you retain access to all the same shows and movies',
    ],
    cohortProof: '3,200 Poseidon users who consolidated streaming subscriptions saved an average of $17/month without reporting content gaps',
    modelInfo: growModelInfo(3),
    dataSources: ['Recurring subscription detection (12 months)', 'Streaming service billing comparison', 'Usage pattern estimation via billing frequency', 'Bundle pricing database'],
  },
  {
    id: 4, title: 'Optimize Credit Card Points Strategy', category: 'Revenue Growth',
    monthlySavings: 16, annualSavings: 192, confidence: 0.88,
    dataBasis: 'Based on 12 months of dining transaction data across your cards',
    situationLabel: 'Your Credit Card Points Strategy',
    currentItems: [
      { name: 'Chase Sapphire Reserve — Dining', cost: 0, usage: 'high', note: '3× points on dining · $800/mo dining spend · earning 2,400 pts/mo' },
      { name: 'Amex Gold Card — Dining (unused)', cost: 0, usage: 'none', note: '4× points on dining · not set as default for dining' },
    ],
    currentTotal: 0,
    comparison: { kind: 'yield', currentApy: 3.0, newApy: 4.0, annualGain: 192 },
    insights: [
      'You\'re earning 3× points on $800/month dining spend with Chase Sapphire Reserve — but your Amex Gold earns 4× on dining',
      'Switching your default dining card to Amex Gold would earn ~800 additional points/month (~9,600/year)',
      'At a conservative 2¢/point valuation, that\'s ~$192/year in additional rewards value',
    ],
    changes: [
      { action: 'switch', item: 'Set Amex Gold as default dining card', from: 'Chase Sapphire 3× ($192/yr value)', to: 'Amex Gold 4× ($384/yr value)', savings: 16 },
    ],
    newTotal: 0,
    alternatives: [],
    ratesAsOf: 'Mar 10, 2026',
    steps: [
      { step: 1, title: 'Set Amex Gold as default for dining', description: 'Update your default payment method for restaurants and food delivery apps to your Amex Gold card.', type: 'manual', estimatedTime: '5 minutes' },
      { step: 2, title: 'Track points accumulation', description: 'Poseidon monitors your dining transactions to confirm Amex Gold is being used and tracks points earned.', type: 'auto', estimatedTime: 'ongoing' },
      { step: 3, title: 'Review quarterly', description: 'Poseidon provides a quarterly points optimization report comparing earning rates across your cards.', type: 'auto', estimatedTime: 'quarterly' },
    ],
    executionType: 'manual',
    factors: [
      'Your $800/month dining spend is earning 3× instead of 4× points — the 1× gap represents ~$192/year in missed rewards value',
      'Both cards are already in your wallet — no new application or annual fee required, just a default card change',
      'The Amex Gold 4× dining multiplier is one of the highest available — optimizing to this card maximizes your existing card portfolio',
    ],
    cohortProof: '1,240 Poseidon users who optimized their card-category matching earned an average of $16/month more in rewards without changing spending habits',
    modelInfo: growModelInfo(4),
    dataSources: ['Dining transaction categorization (12 months)', 'Card rewards rate comparison', 'Points valuation model', 'Category spending analysis'],
  },
  {
    id: 5, title: 'Increase 401(k) to Capture Full Employer Match', category: 'Revenue Growth',
    monthlySavings: 125, annualSavings: 1500, confidence: 0.95,
    dataBasis: 'Based on payroll deduction records and employer benefit plan documentation',
    situationLabel: 'Your 401(k) Contribution',
    currentItems: [
      { name: 'Current contribution (4%)', cost: 0, usage: 'medium', note: '$500/mo pre-tax · employer matches 100% of first 4% ($500/mo)' },
      { name: 'Uncaptured match (4%-8%)', cost: 0, usage: 'none', note: 'Employer matches 50% of next 4% — you\'re leaving $125/mo on the table' },
    ],
    currentTotal: 0,
    comparison: { kind: 'yield', currentApy: 4.0, newApy: 8.0, annualGain: 1500 },
    insights: [
      'You contribute 4% ($500/mo) and receive a 4% employer match ($500/mo) — but your employer also matches 50% on the next 4%',
      'Increasing from 4% to 8% adds $500/mo to your contribution and unlocks $125/mo in additional employer matching',
      'The employer match is an immediate 25% return on the additional $500/mo — no investment can match this guaranteed return',
    ],
    changes: [
      { action: 'increase', item: 'Increase 401(k) contribution from 4% to 8%', from: '4% ($500/mo) + $500 match', to: '8% ($1,000/mo) + $625 match', savings: 125 },
    ],
    newTotal: 0,
    alternatives: [],
    ratesAsOf: 'Mar 10, 2026',
    steps: [
      { step: 1, title: 'Review cash flow impact', description: 'Poseidon analyzed your monthly cash flow — you have $1,200/mo surplus after expenses. The $500/mo increase is pre-tax, reducing take-home by ~$375.', type: 'auto', estimatedTime: '1 minute' },
      { step: 2, title: 'Update contribution on Fidelity', description: 'Log into Fidelity NetBenefits and change your contribution rate from 4% to 8%. Takes effect next pay period.', type: 'semi-auto', estimatedTime: '5 minutes' },
      { step: 3, title: 'Verify next paycheck', description: 'Poseidon confirms the updated deduction and employer match appear on your next paycheck.', type: 'auto', estimatedTime: '2 weeks' },
    ],
    executionType: 'semi-auto',
    factors: [
      'Your employer matches 50% on contributions between 4-8% — increasing to 8% captures $125/mo ($1,500/yr) in free employer money',
      'The additional contribution is pre-tax, reducing your federal tax liability by ~$1,800/yr at the 24% bracket',
      'Your monthly cash flow surplus of $1,200 comfortably absorbs the ~$375/mo take-home reduction',
    ],
    cohortProof: '4,100 Poseidon users who increased 401(k) contributions to capture full employer match gained an average of $1,450/yr in additional employer contributions',
    modelInfo: growModelInfo(5),
    dataSources: ['Payroll deduction records (12 months)', 'Employer benefit plan documentation', 'Monthly cash flow analysis', 'Tax bracket estimation'],
  },
  {
    id: 6, title: 'Open 529 Education Savings Plan', category: 'Revenue Growth',
    monthlySavings: 0, annualSavings: 0, confidence: 0.82,
    dataBasis: 'Based on dependent detection from tax filings and absence of 529 contributions in transaction history',
    situationLabel: 'Education Savings',
    currentItems: [
      { name: 'Current 529 savings', cost: 0, usage: 'none', note: 'No 529 contributions detected · 2 dependents (ages 10, 8) identified from tax data' },
    ],
    currentTotal: 0,
    insights: [
      'You have 2 dependents (ages 10 and 8) but no 529 education savings plan contributions detected in your transaction history',
      'California offers no state tax deduction for 529 contributions, but federal tax-free growth on education expenses is valuable over 8-10 years',
      'Starting now with $250/mo per child could accumulate ~$42,000 each by college age (assuming 7% average annual return)',
    ],
    changes: [
      { action: 'switch', item: 'Open 529 plan for 2 dependents', from: 'No education savings', to: '529 plan — tax-free growth for qualified education expenses', savings: 0 },
    ],
    newTotal: 0,
    alternatives: [
      { name: 'ScholarShare 529 (CA)', detail: 'No state deduction', note: 'California\'s direct-sold plan — low fees, Vanguard/TIAA funds', recommended: true },
      { name: 'Utah my529', detail: 'Top-rated nationally', note: 'Low expense ratios, flexible investment options — available to non-residents', recommended: false },
      { name: 'Coverdell ESA', detail: '$2,000/yr limit', note: 'Broader eligible expenses but lower contribution limit', recommended: false },
    ],
    ratesAsOf: 'Mar 10, 2026',
    steps: [
      { step: 1, title: 'Compare 529 plans', description: 'Poseidon compared the top-rated 529 plans for California residents. ScholarShare 529 recommended for low fees and solid fund options.', type: 'auto', estimatedTime: '2 minutes' },
      { step: 2, title: 'Open 529 accounts', description: 'Open ScholarShare 529 accounts for each dependent. Requires SSN and basic beneficiary information.', type: 'manual', estimatedTime: '20 minutes' },
      { step: 3, title: 'Set up contributions', description: 'Configure monthly auto-contributions from your Chase checking account. Poseidon recommends $250/child/month based on your cash flow.', type: 'semi-auto', estimatedTime: '10 minutes' },
    ],
    executionType: 'manual',
    factors: [
      'Two school-age dependents (ages 10, 8) with no detected education savings — the earlier you start, the more tax-free compounding benefits accumulate',
      '529 earnings grow federally tax-free when used for qualified education expenses (tuition, room & board, books, computers)',
      'At $250/mo per child starting now, you could accumulate approximately $42,000 each by age 18 assuming 7% average annual return',
    ],
    cohortProof: '890 Poseidon users with similar family profiles who opened 529 plans saved an average of $3,200/yr in future education costs through tax-free growth',
    modelInfo: growModelInfo(6),
    dataSources: ['Tax filing dependent data', 'Transaction history (529 contribution search)', '529 plan comparison database', 'Education cost projection model'],
  },
  {
    id: 7, title: 'Negotiate Internet Bill (Rate Increase Detected)', category: 'Efficiency',
    monthlySavings: 25, annualSavings: 300, confidence: 0.76,
    dataBasis: 'Based on 18 months of Comcast billing data showing promotional rate expiration',
    situationLabel: 'Your Internet Bill',
    currentItems: [
      { name: 'Comcast Xfinity (current)', cost: 104.99, usage: 'high', note: '$104.99/mo · was $79.99/mo during promo · 200 Mbps plan' },
    ],
    currentTotal: 104.99,
    comparison: { kind: 'yield', currentApy: 104.99, newApy: 79.99, annualGain: 300 },
    insights: [
      'Your Comcast bill increased from $79.99 to $104.99/mo in February 2026 — your 12-month promotional rate expired',
      'Retention department typically offers 6-12 month promotional extensions when customers call with competitive offers',
      'AT&T Fiber ($70/mo) and Sonic ($65/mo) are available at your address — strong leverage for negotiation',
    ],
    changes: [
      { action: 'reduce', item: 'Negotiate Comcast back to promotional rate', from: 'Comcast $104.99/mo (standard rate)', to: 'Comcast ~$79.99/mo (retention offer)', savings: 25 },
    ],
    newTotal: 79.99,
    alternatives: [
      { name: 'Comcast retention offer', detail: '~$79.99/mo', note: 'Call retention dept with competitor pricing — 73% success rate', recommended: true },
      { name: 'AT&T Fiber', detail: '$70/mo', note: '300 Mbps, no contract, available at your address', recommended: false },
      { name: 'Sonic', detail: '$65/mo', note: 'Fiber where available, no data caps, privacy-focused', recommended: false },
    ],
    ratesAsOf: 'Mar 10, 2026',
    steps: [
      { step: 1, title: 'Prepare negotiation brief', description: 'Poseidon compiled competitor offers and your account history. You\'ve been a customer for 3 years with no missed payments.', type: 'auto', estimatedTime: '1 minute' },
      { step: 2, title: 'Call Comcast retention', description: 'Call 1-800-934-6489, say "cancel service" to reach retention. Mention AT&T Fiber at $70/mo as your alternative.', type: 'manual', estimatedTime: '15 minutes' },
      { step: 3, title: 'Confirm new rate', description: 'Poseidon monitors your next Comcast bill to verify the negotiated promotional rate is applied correctly.', type: 'auto', estimatedTime: '1 billing cycle' },
    ],
    executionType: 'semi-auto',
    factors: [
      'Your Comcast bill jumped 31% ($79.99 → $104.99) when the promotional period ended — this is the #1 most common bill increase Poseidon detects',
      'Comcast retention offers are available to 73% of customers who call with competitive alternatives — AT&T Fiber at $70/mo is strong leverage',
      'Your 3-year tenure with zero missed payments gives you strong negotiating position — Comcast\'s customer acquisition cost exceeds $300',
    ],
    cohortProof: '2,800 Poseidon users who negotiated internet bills after promotional expiration saved an average of $23/month',
    modelInfo: growModelInfo(7),
    dataSources: ['Comcast billing history (18 months)', 'Competitor availability check (address-level)', 'ISP retention offer success rate database', 'Customer tenure analysis'],
  },
  {
    id: 8, title: 'Daily Cash Pooling via FedNow Sweep', category: 'Revenue Growth',
    monthlySavings: 35, annualSavings: 420, confidence: 0.88,
    dataBasis: 'Based on 12 months of Chase checking balance patterns and FedNow-enabled institution rates',
    situationLabel: 'Your Overnight Cash',
    currentItems: [
      { name: 'Chase checking idle balance', cost: 0, usage: 'low', note: 'Average $9,000 idle overnight · earning 0.01% APY · $0.90/yr interest' },
    ],
    currentTotal: 0,
    comparison: { kind: 'yield', currentApy: 0.01, newApy: 4.50, annualGain: 420 },
    insights: [
      'Your Chase checking account averages $9,000 in idle balance overnight after all scheduled payments clear',
      'FedNow instant payment rails enable nightly sweeps — move idle funds to a 4.50% APY account at 11 PM, return by 6 AM',
      'This generates ~$35/month ($420/year) in interest on money that\'s currently earning virtually nothing overnight',
    ],
    changes: [
      { action: 'switch', item: 'Enable nightly FedNow cash sweep', from: 'Chase checking 0.01% APY overnight ($0.90/yr)', to: 'Marcus HYSA 4.50% APY overnight (~$420/yr)', savings: 35 },
    ],
    newTotal: 0,
    alternatives: [
      { name: 'Marcus by Goldman Sachs', detail: '4.50% APY', note: 'FedNow-enabled, FDIC insured, instant transfer capability', recommended: true },
      { name: 'Wealthfront Cash', detail: '4.25% APY', note: 'FedNow-enabled, automatic sweep feature built-in', recommended: false },
      { name: 'Manual weekly transfer', detail: '4.50% APY', note: 'Lower interest capture but simpler setup — no overnight automation needed', recommended: false },
    ],
    ratesAsOf: 'Mar 10, 2026',
    steps: [
      { step: 1, title: 'Verify FedNow compatibility', description: 'Poseidon confirmed both Chase and Marcus support FedNow instant transfers. Round-trip time: under 30 seconds.', type: 'auto', estimatedTime: '1 minute' },
      { step: 2, title: 'Set sweep parameters', description: 'Configure sweep rules: maintain $3,000 minimum in Chase checking, sweep excess at 11 PM, return by 6 AM daily.', type: 'semi-auto', estimatedTime: '5 minutes' },
      { step: 3, title: 'Activate nightly sweep', description: 'Authorize the automated FedNow sweep. Poseidon manages the nightly cycle and adjusts for upcoming large transactions.', type: 'semi-auto', estimatedTime: '2 minutes' },
    ],
    executionType: 'auto',
    factors: [
      'Your Chase checking averages $9,000 idle overnight — FedNow instant rails make it possible to earn 4.50% APY on this balance without any liquidity risk',
      'FedNow transfers settle in under 30 seconds, 24/7/365 — your money is back in Chase before any morning transactions process',
      'Poseidon dynamically adjusts the sweep amount based on upcoming scheduled payments, avoiding any risk of insufficient funds',
    ],
    cohortProof: '1,850 Poseidon users using FedNow cash sweeps earn an average of $32/month in additional interest on idle checking balances',
    modelInfo: growModelInfo(8),
    dataSources: ['Chase checking balance history (12 months)', 'FedNow institution directory', 'High-yield savings rate comparison', 'Scheduled payment analysis'],
  },
]

export const CANONICAL_RECOMMENDATIONS_SUMMARY = CANONICAL_RECOMMENDATION_DETAILS.map(r => ({
  rank: r.id,
  title: r.title,
  monthly: r.monthlySavings,
  annual: r.annualSavings,
  confidence: r.confidence,
}))

const EXECUTION_TO_DIFFICULTY: Record<ExecutionType, 'Easy' | 'Medium' | 'Hard'> = {
  auto: 'Easy',
  'semi-auto': 'Medium',
  manual: 'Hard',
  hybrid: 'Hard',
}

export const CANONICAL_RECOMMENDATIONS_FOR_LIST: RecommendationListItem[] = CANONICAL_RECOMMENDATION_DETAILS.map((r, i) => {
  const factorNames = r.factors.slice(0, 3)
  const totalFactors = factorNames.length
  const baseWeight = Math.round((1 / totalFactors) * 100) / 100
  return {
    id: r.id,
    rank: i + 1,
    title: r.title,
    description: r.dataBasis,
    category: r.category as 'Efficiency' | 'Risk Mitigation' | 'Revenue Growth',
    difficulty: EXECUTION_TO_DIFFICULTY[r.executionType],
    monthlySavings: r.monthlySavings,
    annualSavings: r.annualSavings,
    confidence: r.confidence,
    shapFactors: factorNames.map((name, j) => ({
      name: name.length > 40 ? name.slice(0, 37) + '...' : name,
      weight: j === 0 ? 1 - baseWeight * (totalFactors - 1) : baseWeight,
    })),
    evidence: r.cohortProof,
    modelVersion: `${r.modelInfo.name} v${r.modelInfo.version}`,
    auditId: r.modelInfo.auditId,
  }
})

// ─── Accounts & Balance Sheet ─────────────────────────────────────────────

const ACCOUNTS: AccountEntity[] = [
  { id: 'ACCT-001', label: 'Chase Total Checking', institution: 'Chase', last4: '3847', type: 'checking', balanceUsd: 12450.32, apy: 0.01 },
  { id: 'ACCT-002', label: 'Chase Savings', institution: 'Chase', last4: '7733', type: 'savings', balanceUsd: 8200.00, apy: 0.01 },
  { id: 'ACCT-003', label: 'Amex Gold Card', institution: 'Amex', last4: '4821', type: 'credit-card', balanceUsd: -2340.87, apr: 21.24, limit: 15000 },
  { id: 'ACCT-004', label: 'Chase Sapphire Reserve', institution: 'Chase', last4: '9156', type: 'credit-card', balanceUsd: -890.45, apr: 24.99, limit: 25000 },
  { id: 'ACCT-005', label: 'Fidelity 401(k)', institution: 'Fidelity', last4: '9102', type: 'retirement', balanceUsd: 45230.18, ytdReturn: 8.2 },
  { id: 'ACCT-006', label: 'Fidelity Roth IRA', institution: 'Fidelity', last4: '6204', type: 'roth-ira', balanceUsd: 18540.92, ytdReturn: 7.8 },
  { id: 'ACCT-007', label: 'Fidelity Individual Brokerage', institution: 'Fidelity', last4: '5521', type: 'brokerage', balanceUsd: 12850.67, ytdReturn: 5.4 },
]

const GOALS: GoalEntity[] = [
  { id: 'GOAL-001', title: 'Save for Condo Down Payment', currentUsd: 12850.67, targetUsd: 100000, monthlyContributionUsd: 500, engine: 'Grow' },
  { id: 'GOAL-002', title: '6-Month Emergency Fund', currentUsd: 8200, targetUsd: 39000, monthlyContributionUsd: 420, engine: 'Grow' },
]

// ─── Canonical Universe Export ───────────────────────────────────────────────

export const CANONICAL_UNIVERSE: CanonicalUniverseV1 = {
  schemaVersion: '1.1.0',
  generatedAt: '2026-03-10T09:00:00-07:00',
  metrics: {
    systemConfidence: DEMO_THREAD.systemConfidence,
    complianceScore: DEMO_THREAD.complianceScore,
    pendingActions: EXECUTE_ACTIONS.length,
    monthlyOptimizationCurrentUsd: 0,
    monthlyOptimizationPotentialUsd: RECOMMENDATIONS.reduce((s, r) => s + r.projectedBenefitUsd, 0),
    decisionsAuditedTotal: VERIFIED_DECISIONS + PENDING_REVIEW_DECISIONS + FLAGGED_DECISIONS,
    verifiedDecisions: VERIFIED_DECISIONS,
    pendingReviewDecisions: PENDING_REVIEW_DECISIONS,
    flaggedDecisions: FLAGGED_DECISIONS,
    liquidityReserve: {
      percent: DEMO_THREAD.liquidityReserve.percent,
      currentUsd: DEMO_THREAD.liquidityReserve.current,
      targetUsd: DEMO_THREAD.liquidityReserve.target,
    },
    engineBreakdown: { Protect: 27, Grow: 22, Execute: 11, Govern: 7 },
    platformProfileCount: 184_290,
    architecturalTrust: {
      autoExecutionsWithoutConsent: 0,
      auditCoveragePercent: 100,
      falsePositiveRate: 0.008,
      llmRetentionDays: 0,
      llmTrainingOptOut: true,
    },
    cohort: {
      recommendationAcceptanceRate: 0.89,
      avgMonthlySavingsUsd: 438,
      fraudTrend: {
        label: 'Credential-stuffing attacks up 31% this quarter',
        changePercent: 31,
        period: 'Q1 2026',
        factors: [
          { label: 'VPN-based credential stuffing', value: 0.88 },
          { label: 'Card-not-present fraud', value: 0.76 },
          { label: 'Subscription billing errors', value: 0.62 },
        ],
      },
      cohortSize: 12847,
      projected3yAdvantageUsd: CANONICAL_PROJECTED_3Y_ADVANTAGE,
      protectPerformance: {
        riskIncidentsFlagged: 10,
        avgMonthlyExposureUsd: 387,
      },
    },
    councilMetrics: {
      falsePositiveReductionPercent: 34,
      recommendationChangedPercent: 22,
      modelDisagreementRate: 0.31,
      avgTimeToDecisionMinutes: 2.4,
      humanOverrideRate: 0.08,
      confidenceSpread: { min: 0.40, max: 0.94 },
    },
    cohortHeadlines: {
      dashboard: 'Poseidon users with your profile save $438/mo on average — you\'re saving $0/mo currently',
      protect: 'Suspicious login from Oslo correlated with unauthorized purchase — immediate review recommended',
      grow: '12,847 similar users who acted on their top recommendations saved $4,200/year',
      execute: '89% of users approve their top recommendation within 24 hours',
      govern: 'Poseidon\'s models disagreed on 31% of decisions before presenting them to you',
    },
  },
  entities: {
    criticalAlert: {
      id: DEMO_THREAD.criticalAlert.id,
      amountUsd: DEMO_THREAD.criticalAlert.amount,
      counterparty: DEMO_THREAD.criticalAlert.counterparty,
      confidence: DEMO_THREAD.criticalAlert.confidence,
      transactionType: 'Card-not-present purchase',
      signalId: DEMO_THREAD.criticalAlert.signalId ?? 'PRT-2026-0310-001',
    },
    protectThreats: PROTECT_THREATS,
    recommendations: RECOMMENDATIONS,
    executeActions: EXECUTE_ACTIONS,
    governAuditEntries: GOVERN_AUDIT_ENTRIES,
    dashboardActivities: DASHBOARD_ACTIVITIES,
    events: CANONICAL_EVENTS,
    accounts: ACCOUNTS,
    goals: GOALS,
  },
  balanceSheet: {
    accounts: ACCOUNTS,
    totalAssets: 97272.09,
    totalLiabilities: 3231.32,
    netWorth: 94040.77,
    monthlyIncome: 15000,
    monthlyExpenses: 6500,
  },
  relations: {
    alertToAction: {
      'THR-002': ['EXE-004'],
      'THR-004': ['EXE-004'],
      'THR-006': ['EXE-006'],
      'THR-009': ['EXE-009'],
    },
    recommendationToAction: {
      'REC-001': ['EXE-002'],
      'REC-005': ['EXE-005'],
      'REC-007': ['EXE-007'],
      'REC-008': ['EXE-008'],
    },
    actionToDecision: {
      'EXE-001': ['GV-2026-0310-003'],
      'EXE-002': ['GV-2026-0310-003'],
      'EXE-003': ['GV-2026-0307-006'],
      'EXE-004': ['GV-2026-0310-002'],
      'EXE-005': ['GV-2026-0309-012'],
      'EXE-006': ['GV-2026-0309-007'],
      'EXE-007': ['GV-2026-0307-014'],
      'EXE-008': ['GV-2026-0306-015'],
      'EXE-009': ['GV-2026-0301-010'],
    },
    eventToChildren: Object.fromEntries(
      CANONICAL_EVENTS.map((e) => [e.id, e.children]),
    ),
  },
}

function formatUsd(value: number): string {
  return `$${value.toLocaleString()}`
}
